### ISSUE TITLE
[Bug]: pio boards is broken

### ISSUE THREAD

**Issue by jmgurney** [meshtastic/firmware#2353]
### Category

Other

### Hardware

Not Applicable

### Firmware Version

bb885a51102c5

### Description

Starting with bb885a51102c5, the command `pio boards` breaks (discovered via git bisect, so possible that there are more recently commits that it briefly worked).

```
$ git checkout bb885a51102c5
HEAD is now at bb885a51 add a variant based on the nrf52840-dk but with a RC clock. Because I was dumb and accidentally ran some code that configured gpio 0 as an output and that was enough to smoke the xtal that was preinstalled between P0.0 and P0.1.
$ pio --version
PlatformIO Core, version 6.1.6
$ pio boards
Error: Traceback (most recent call last):
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/commands/boards.py", line 34, in cli
    for board in _get_boards(installed):
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/commands/boards.py", line 75, in _get_boards
    return pm.get_installed_boards() if installed else pm.get_all_boards()
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/package/manager/platform.py", line 124, in get_all_boards
    boards = self.get_installed_boards()
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/util.py", line 56, in wrapper
    self.cache[key] = (time.time(), func(*args, **kwargs))
  File "/Users/jmg/github/BlueSCSI/p/lib/python3.10/site-packages/platformio/package/manager/platform.py", line 112, in get_installed_boards
    for config in p.get_boards().values():
  File "/Users/jmg/.platformio/platforms/ststm32/platform.py", line 121, in get_boards
    result[key] = self._add_default_debug_tools(result[key])
  File "/Users/jmg/.platformio/platforms/ststm32/platform.py", line 165, in _add_default_debug_tools
    assert debug.get("openocd_target"), (
AssertionError: Missed target configuration for ppr

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

```

But even master as of fddc49273ec51e returns an error, just for a different board:
```
AssertionError: Missed target configuration for eink0.1
```

**Comment by caveman99** [comment]
that is a sign you toolchain cache is broken. delete everything from your project .pio folder and rerun. if that does not help (it usually doesnt) remove ~/.platformio except for the penv folder. After reinstalling PIO on the next call of VSCode it usually works again.

eink0.1 is just the first board definition it finds in the project. if you shuffle them around it will complain about another one.
