### ISSUE TITLE
[Bug]: t-beam won't stay shutdown

### ISSUE THREAD

**Issue by 65a** [meshtastic/firmware#4796]
### Category

Hardware Compatibility

### Hardware

T-Beam

### Firmware Version

2.5.0.9ac0e26

### Description

Recent lilygo t-beam v1.x

Shutting down the device via user long-press or android app works, but after 30s, the t-beam board will boot up again. It appears impossible to force the board off without removing the 18650.

### Relevant log output

```Shell
n/a
```

**Comment by todd-herbert** [comment]
I can replicate this on T-Beam V1.2 and latest master
First guess, maybe shutdown is hanging while trying to end I2C?

```
INFO  | ??:??:?? 1453 [Button] Shutdown from long press
INFO  | ??:??:?? 1456 [Button] Shutting down
INFO  | ??:??:?? 1456 [Button] Entering deep sleep forever
INFO  | ??:??:?? 1456 [Button] Disable bluetooth until reboot
INFO  | ??:??:?? 1456 [Button] GPS deep sleep!
INFO  | ??:??:?? 1456 [Button] GPS power state moving from ACTIVE to OFF
INFO  | ??:??:?? 1457 [Button] Turning off screen
INFO  | ??:??:?? 1457 [Button] Saving /prefs/config.proto
INFO  | ??:??:?? 1457 [Button] Saving /prefs/module.proto
INFO  | ??:??:?? 1457 [Button] Saving /prefs/channels.proto
INFO  | ??:??:?? 1458 [Button] Saving /prefs/db.proto
[1458821][E][Wire.cpp:526] write(): NULL TX buffer pointer
[1458827][E][Wire.cpp:448] endTransmission(): NULL TX buffer pointer
E (1589348) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (1589348) task_wdt:  - loopTask (CPU 1)
E (1589348) task_wdt: Tasks currently running:
E (1589348) task_wdt: CPU 0: IDLE0
E (1589348) task_wdt: CPU 1: IDLE1
E (1589348) task_wdt: Aborting.

abort() was called at PC 0x401584a0 on core 0


Backtrace: 0x400842c5:0x3ffbfabc |<-CORRUPTED




ELF file SHA256: bf8e607e07926086

E (45793) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
E (852) esp_core_dump_flash: No core dum���ѥѥ���found!
E (852) esp_core_dump_flash: No core dump partition found!
[    11][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[   474][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
��@INFO  | ??:??:?? 0 

//\ E S H T /\ S T / C

INFO  | ??:??:?? 0 Booted, wake cause 0 (boot count 1), reset_reason=reset
DEBUG | ??:??:?? 0 Filesystem files (16384/1048576 Bytes):
DEBUG | ??:??:?? 0  /prefs/cannedConf.proto (31 Bytes)
DEBUG | ??:??:?? 0  /prefs/channels.proto (53 Bytes)
DEBUG | ??:??:?? 0  /prefs/config.proto (170 Bytes)
DEBUG | ??:??:?? 0  /prefs/db.proto (396 Bytes)
DEBUG | ??:??:?? 0  /prefs/module.proto (116 Bytes)
[   589][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=21 scl=22 freq=100000
[   603][I][XPowersCommon.tpp:248] begin(): SDA:21 SCL:22
[   608][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
INFO  | ??:??:?? 0 AXP2101 PMU init succeeded, using AXP2101 PMU
[   631][D][XPowersAXP2101.tpp:2791] setInterruptImpl(): DISABLE - HEX:0xffffffff BIN:
DEBUG | ??:??:?? 0 =======================================================================
DEBUG | ??:??:?? 0 DC1  : +   Voltage:3300 mV
DEBUG | ??:??:?? 0 DC2  : -   Voltage:500 mV 
DEBUG | ??:??:?? 0 DC3  : -   Voltage:500 mV
DEBUG | ??:??:?? 0 DC4  : -   Voltage:1800 mV 
DEBUG | ??:??:?? 0 ALDO1: -   Voltage:1800 mV
DEBUG | ??:??:?? 0 ALDO2: +   Voltage:3300 mV 
DEBUG | ??:??:?? 0 ALDO3: +   Voltage:3300 mV
DEBUG | ??:??:?? 0 ALDO4: -   Voltage:3300 mV
DEBUG | ??:??:?? 0 BLDO1: -   Voltage:1800 mV 
DEBUG | ??:??:?? 0 BLDO2: -   Voltage:3300 mV
DEBUG | ??:??:?? 0 =======================================================================
DEBUG | ??:??:?? 0 Battery: usbPower=1, isCharging=0, batMv=-1, batPct=0
INFO  | ??:??:?? 0 Scanning for i2c devices...
[   731][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
DEBUG | ??:??:?? 0 Scanning for I2C devices on port 1
DEBUG | ??:??:?? 0 I2C device found at address 0x34
INFO  | ??:??:?? 0 axp192/axp2101 PMU found
DEBUG | ??:??:?? 0 I2C device found at address 0x3c
INFO  | ??:??:?? 0 ssd1306 display found
INFO  | ??:??:?? 0 ssd1306 display found
DEBUG | ??:??:?? 0 0x4 subtype probed in 2 tries 
INFO  | ??:??:?? 0 2 I2C devices found
DEBUG | ??:??:?? 0 acc_info = 0
INFO  | ??:??:?? 0 S:B:4,2.5.1.ed13105ae
DEBUG | ??:??:?? 0 Total heap: 187432
DEBUG | ??:??:?? 0 Free heap: 153312
DEBUG | ??:??:?? 0 Total PSRAM: 4192107
DEBUG | ??:??:?? 0 Free PSRAM: 4191863
DEBUG | ??:??:?? 0 NVS: UsedEntries 98, FreeEntries 532, AllEntries 630, NameSpaces 4
DEBUG | ??:??:?? 0 Setup Preferences in Flash Storage
DEBUG | ??:??:?? 0 Number of Device Reboots: 20
ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0x105 (ESP_ERR_NOT_FOUND) at 0x4009894b
  #0  0x4009894b in _esp_error_check_failed_without_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_err.c:37

file: "src/platform/esp32/BleOta.cpp" line 16
func: static const esp_partition_t* BleOta::findEspOtaAppPartition()
expression: esp_ota_get_partition_description(part, &app_desc)
ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x4009894b
  #0  0x4009894b in _esp_error_check_failed_without_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_err.c:37

file: "src/platform/esp32/BleOta.cpp" line 30
func: static String BleOta::getOtaAppVersion()
expression: esp_ota_get_partition_description(part, &app_desc)
INFO  | ??:??:?? 0 No OTA firmware available
INFO  | ??:??:?? 0 Initializing NodeDB
INFO  | ??:??:?? 0 Loading /prefs/db.proto
INFO  | ??:??:?? 0 Loaded /prefs/db.proto successfully
INFO  | ??:??:?? 0 Loaded saved devicestate version 23, with nodecount: 1
INFO  | ??:??:?? 0 Loading /prefs/config.proto
INFO  | ??:??:?? 0 Loaded /prefs/config.proto successfully
INFO  | ??:??:?? 0 Loaded saved config version 23
INFO  | ??:??:?? 0 Loading /prefs/module.proto
INFO  | ??:??:?? 0 Loaded /prefs/module.proto successfully
INFO  | ??:??:?? 0 Loaded saved moduleConfig version 23
INFO  | ??:??:?? 1 Loading /prefs/channels.proto
INFO  | ??:??:?? 1 Loaded /prefs/channels.proto successfully
INFO  | ??:??:?? 1 Loaded saved channelFile version 23
[  1017][E][vfs_api.cpp:105] open(): /littlefs/oem/oem.proto does not exist, no permits for creation
ERROR | ??:??:?? 1 Could not open / read /oem/oem.proto
DEBUG | ??:??:?? 1 cleanupMeshDB purged 0 entries
DEBUG | ??:??:?? 1 Using nodenum 0x1c498f44 
DEBUG | ??:??:?? 1 Old Pubkey: 21 e3 cd de 4a 43 0a 03 aa cf 33 cb e4 fb 74 1d ce 97 73 8e 21 89 db a8 1a bc 27 14 71 67 a8 15 
INFO  | ??:??:?? 1 Using saved PKI keys
DEBUG | ??:??:?? 1 Number of Device Reboots: 20
DEBUG | ??:??:?? 1 Expanding short PSK #1
INFO  | ??:??:?? 1 Wanted region 6, using ANZ
INFO  | ??:??:?? 1 Saving /prefs/db.proto
DEBUG | ??:??:?? 1 Using GPIO38 for button
DEBUG | ??:??:?? 1 SPI.begin(SCK=5, MISO=19, MOSI=27, NSS=18)
DEBUG | ??:??:?? 1 Set Timezone to GMT0
DEBUG | ??:??:?? 1 Read RTC time as 1544
INFO  | ??:??:?? 1 GPS power state moving from OFF to ACTIVE
DEBUG | ??:??:?? 1 Using GPIO34 for GPS RX
DEBUG | ??:??:?? 1 Using GPIO12 for GPS TX
DEBUG | ??:??:?? 1 NeighborInfoModule is disabled
INFO  | ??:??:?? 1 Rotary initialized (25, 14, 13)
DEBUG | ??:??:?? 1 Up/down/press GPIO initialized (25, 14, 13)
DEBUG | ??:??:?? 1 Rescanning for I2C keyboard
DEBUG | ??:??:?? 1 Scanning for I2C devices on port 1
DEBUG | ??:??:?? 1 Scanning address 0x1f
DEBUG | ??:??:?? 1 Scanning address 0x55
DEBUG | ??:??:?? 1 Scanning address 0x5f
INFO  | ??:??:?? 1 Loading /prefs/cannedConf.proto
INFO  | ??:??:?? 1 Loaded /prefs/cannedConf.proto successfully
DEBUG | ??:??:?? 1 CannedMessage 2 is: 'message 3'
INFO  | ??:??:?? 1 CannedMessageModule is enabled
INFO  | ??:??:?? 1 External Notification Module Disabled
INFO  | ??:??:?? 1 Turning on screen
DEBUG | ??:??:?? 1 haveGlyphs=1
DEBUG | ??:??:?? 1 Module wants a UI Frame
DEBUG | ??:??:?? 1 Module wants a UI Frame
DEBUG | ??:??:?? 1 RF95Interface(cs=18, irq=26, rst=23, busy=33)
INFO  | ??:??:?? 1 Starting meshradio init...
DEBUG | ??:??:?? 1 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=0, time 231 ms
DEBUG | ??:??:?? 1 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=253, time 2115 ms
INFO  | ??:??:?? 1 Radio freq=927.875, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 1 Set radio: region=ANZ, name=LongFast, config=0, ch=51, power=30
INFO  | ??:??:?? 1 Radio myRegion->freqStart -> myRegion->freqEnd: 915.000000 -> 928.000000 (13.000000 MHz)
INFO  | ??:??:?? 1 Radio myRegion->numChannels: 52 x 250.000kHz
INFO  | ??:??:?? 1 Radio channel_num: 52
INFO  | ??:??:?? 1 Radio frequency: 927.875000
INFO  | ??:??:?? 1 Slot time: 77 msec
INFO  | ??:??:?? 1 Set radio: final power level=20
INFO  | ??:??:?? 1 RF95 init result -2
INFO  | ??:??:?? 1 Frequency set to 927.875000
INFO  | ??:??:?? 1 Bandwidth set to 250.000000
INFO  | ??:??:?? 1 Power output set to 20
WARN  | ??:??:?? 1 Failed to find RF95 radio
DEBUG | ??:??:?? 1 SX126xInterface(cs=18, irq=33, rst=23, busy=32)
DEBUG | ??:??:?? 1 SX126X_DIO3_TCXO_VOLTAGE defined, using DIO3 as TCXO reference voltage at 1.800000 V
INFO  | ??:??:?? 1 Starting meshradio init...
DEBUG | ??:??:?? 1 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=0, time 231 ms
DEBUG | ??:??:?? 1 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=253, time 2115 ms
INFO  | ??:??:?? 1 Radio freq=927.875, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 1 Set radio: region=ANZ, name=LongFast, config=0, ch=51, power=30
INFO  | ??:??:?? 1 Radio myRegion->freqStart -> myRegion->freqEnd: 915.000000 -> 928.000000 (13.000000 MHz)
INFO  | ??:??:?? 1 Radio myRegion->numChannels: 52 x 250.000kHz
INFO  | ??:??:?? 1 Radio channel_num: 52
INFO  | ??:??:?? 1 Radio frequency: 927.875000
INFO  | ??:??:?? 1 Slot time: 77 msec
INFO  | ??:??:?? 1 Set radio: final power level=22
INFO  | ??:??:?? 11 SX126x init result -2
WARN  | ??:??:?? 11 Failed to find SX1262 radio
DEBUG | ??:??:?? 11 SX126xInterface(cs=18, irq=33, rst=23, busy=32)
DEBUG | ??:??:?? 11 SX126X_DIO3_TCXO_VOLTAGE defined, using DIO3 as TCXO reference voltage at 1.800000 V
INFO  | ??:??:?? 11 Starting meshradio init...
DEBUG | ??:??:?? 11 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=0, time 231 ms
DEBUG | ??:??:?? 11 (bw=250, sf=11, cr=4/5) packet symLen=8 ms, payloadSize=253, time 2115 ms
INFO  | ??:??:?? 11 Radio freq=927.875, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 11 Set radio: region=ANZ, name=LongFast, config=0, ch=51, power=30
INFO  | ??:??:?? 11 Radio myRegion->freqStart -> myRegion->freqEnd: 915.000000 -> 928.000000 (13.000000 MHz)
INFO  | ??:??:?? 11 Radio myRegion->numChannels: 52 x 250.000kHz
INFO  | ??:??:?? 11 Radio channel_num: 52
INFO  | ??:??:?? 11 Radio frequency: 433.125000
INFO  | ??:??:?? 11 Slot time: 77 msec
INFO  | ??:??:?? 11 Set radio: final power level=22
INFO  | ??:??:?? 22 SX126x init result -2
WARN  | ??:??:?? 22 Failed to find SX1268 radio
INFO  | ??:??:?? 22 Not using WIFI
ERROR | ??:??:?? 22 NOTE! Recording critical error 3 at src/main.cpp:1058
```

**Comment by todd-herbert** [comment]
The issue seems to have been created by #4418, affecting releases later than v2.4.2. 
When preparing to deep-sleep, `Wire.end()` is called before the T-Beam's PMU can be configured, which requires I2C.
