### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'meshtastic.mesh_pb2'

### ISSUE THREAD

**Issue by spin1024** [meshtastic/firmware#4876]
### Category

Other

### Hardware

Other

### Firmware Version

---

### Description

meshtastic-flasher
not starting

### Relevant log output

```Shell
Traceback (most recent call last):
  File "/home/user/.local/bin/meshtastic-flasher", line 5, in <module>
    from meshtastic_flasher.main import main
  File "/home/user/.local/lib/python3.8/site-packages/meshtastic_flasher/main.py", line 11, in <module>
    import meshtastic_flasher.form
  File "/home/user/.local/lib/python3.8/site-packages/meshtastic_flasher/form.py", line 32, in <module>
    from meshtastic_flasher.settings import Settings
  File "/home/user/.local/lib/python3.8/site-packages/meshtastic_flasher/settings.py", line 10, in <module>
    from meshtastic_flasher.user_form import UserForm
  File "/home/user/.local/lib/python3.8/site-packages/meshtastic_flasher/user_form.py", line 8, in <module>
    import meshtastic.mesh_pb2
ModuleNotFoundError: No module named 'meshtastic.mesh_pb2'
```

**Comment by spin1024** [comment]
I have trouble with flash web
I have healtec 2_1 and not fount firmware

trouble is how flashing my device with old firmweare?
